version: '3'
services:

  front-end:
    build: ./frontend
    container_name: front-end
    ports:
      - ${FRONT_PORT}:8080
    environment:
      - VUE_APP_API_URL=back-end
    links:
      - back-end

  back-end:
    build: ./backend
    container_name: back-end
    environment:
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_USERNAME: ${MONGO_DB_USER}
      MONGO_PASSWORD: ${MONGO_DB_PASS}
      MONGO_PORT: ${MONGO_DB_PORT}
    ports:
      - ${BACK_PORT}:8080
    links:
      - mongo-db
    depends_on:
        - mongo-db

  mongo-db:
    image: mongo:latest
    restart: always
    container_name: mongo-db
    environment:
      NAME: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASS}
    ports:
      - ${MONGO_DB_PORT}:27017